export const headerSectionContent = {
  EN: {
    request: "REQUEST",
    home: "HOME",
    creator: "CREATOR",
    editor: "EDITOR",
    logout: "Log Out",
  },
  HI: {
    request: "अनुरोध",
    home: "घर",
    creator: "निर्माता",
    editor: "संपादक",
    logout: "लॉग आउट",
  },
  TE: {
    request: "అభ్యర్థన",
    home: "ఇల్లు",
    creator: "సృష్టికర్త",
    editor: "సంపాదకుడు",
    logout: "లాగ్ అవుట్ చేయండి",
  },
  ZH: {
    request: "要求",
    home: "家",
    creator: "創造者",
    editor: "編輯",
    logout: "登出",
  },
  ES: {
    request: "PEDIDO",
    home: "HOGAR",
    creator: "CREADOR",
    editor: "EDITOR",
    logout: "Cerrar sesión",
  },
  FR: {
    request: "DEMANDE",
    home: "MAISON",
    creator: "CRÉATEUR",
    editor: "ÉDITEUR",
    logout: "Se déconnecter",
  },
  AR: {
    request: "طلب",
    home: "بيت",
    creator: "المنشئ",
    editor: "محرر",
    logout: "تسجيل خروج",
  },
  BN: {
    request: "অনুরোধ",
    home: "বাড়ি",
    creator: "সৃষ্টিকর্তা",
    editor: "সম্পাদক",
    logout: "প্রস্থান",
  },
  RU: {
    request: "ЗАПРОС",
    home: "ДОМ",
    creator: "СОЗДАТЕЛЬ",
    editor: "РЕДАКТОР",
    logout: "Выйти",
  },
  PT: {
    request: "SOLICITAR",
    home: "LAR",
    creator: "CRIADOR",
    editor: "EDITOR",
    logout: "Sair",
  },
  UR: {
    request: "درخواست کریں۔",
    home: "گھر",
    creator: "خالق",
    editor: "ایڈیٹر",
    logout: "لاگ آوٹ",
  },
};
