export const requestSectionContent = {
  EN: {
    renderLoadingContent: {
      loadingText: "Please wait. We are on your request",
    },
    renderSubmitMessageContent: {
      successMessage: "Request made successfully",
      clientErrorMessage: "Error uploading. Please try again",
      serverErrorMessage: "Upload failed. Please try again",
      goBack: "go back",
    },
    renderRequestSectionContent: {
      heading: "Make a Request By",
      myFileText: "Your browser does not support the video tag",
      uploadVideoText: "Click here to upload your video",
      uploadThumbnailText: "Click here to upload your thumbnail",
      title_: "Title (required)",
      description_: "Description (required)",
      audience_: "Audience(required)",
      madeForKids: "Yes, made for kids",
      notMadeForKids: "No, not made for kids",
      visibility_: "Visibility (required)",
      select: "select",
      public_: "public",
      private_: "private",
      category: "Category (required)",
      selectCategory: "Select Category",
      creatorInvitationCode: "Creator Invitation Code (required)",
      submit: "Submit",
    },
  },
  HI: {
    renderLoadingContent: {
      loadingText: "कृपया प्रतीक्षा करें। हम आपके अनुरोध पर हैं",
    },
    renderSubmitMessageContent: {
      successMessage: "अनुरोध सफलतापूर्वक किया गया",
      clientErrorMessage: "अपलोड करने में त्रुटि. कृपया पुन: प्रयास करें",
      serverErrorMessage: "अपलोड विफल। कृपया पुन: प्रयास करें",
      goBack: "वापस जाओ",
    },
    renderRequestSectionContent: {
      heading: "द्वारा अनुरोध करें",
      myFileText: "आपका ब्राउज़र में वीडियो टैग समर्थित नहीं है",
      uploadVideoText: "अपना वीडियो अपलोड करने के लिए यहां क्लिक करें",
      uploadThumbnailText: "अपना थंबनेल अपलोड करने के लिए यहां क्लिक करें",
      title_: "शीर्षक (आवश्यक)",
      description_: "विवरण (आवश्यक)",
      audience_: "श्रोता(आवश्यक)",
      madeForKids: "हाँ, बच्चों के लिए बनाया गया है",
      notMadeForKids: "नहीं, बच्चों के लिए नहीं बनाया गया",
      visibility_: "दृश्यता (आवश्यक)",
      select: "चुनना",
      public_: "जनता",
      private_: "निजी",
      category: "श्रेणी (आवश्यक)",
      selectCategory: "श्रेणी चुनना",
      creatorInvitationCode: "निर्माता आमंत्रण कोड (आवश्यक)",
      submit: "जमा करना",
    },
  },
  TE: {
    renderLoadingContent: {
      loadingText: "దయచేసి వేచి ఉండండి. మేము మీ అభ్యర్థనపై ఉన్నాము",
    },
    renderSubmitMessageContent: {
      successMessage: "అభ్యర్థన విజయవంతంగా చేయబడింది",
      clientErrorMessage: "అప్‌లోడ్ చేయడంలో లోపం. దయచేసి మళ్లీ ప్రయత్నించండి",
      serverErrorMessage: "అప్లోడ్ విఫలమైంది. దయచేసి మళ్లీ ప్రయత్నించండి",
      goBack: "వెనక్కి వెళ్ళు",
    },
    renderRequestSectionContent: {
      heading: "ద్వారా అభ్యర్థన చేయండి",
      myFileText: "మీ బ్రౌజర్ వీడియో ట్యాగ్‌కు మద్దతు ఇవ్వదు",
      uploadVideoText: "మీ వీడియోను అప్‌లోడ్ చేయడానికి ఇక్కడ క్లిక్ చేయండి",
      uploadThumbnailText:
        "మీ సూక్ష్మచిత్రాన్ని అప్‌లోడ్ చేయడానికి ఇక్కడ క్లిక్ చేయండి",
      title_: "శీర్షిక (అవసరం)",
      description_: "వివరణ (అవసరం)",
      audience_: "ప్రేక్షకులు (అవసరం)",
      madeForKids: "అవును, పిల్లల కోసం రూపొందించబడింది",
      notMadeForKids: "లేదు, పిల్లల కోసం రూపొందించబడలేదు",
      visibility_: "దృశ్యమానత (అవసరం)",
      select: "ఎంచుకోండి",
      public_: "ప్రజా",
      private_: "ప్రైవేట్",
      category: "వర్గం (అవసరం)",
      selectCategory: "వర్గం ఎంచుకోండి",
      creatorInvitationCode: "సృష్టికర్త ఆహ్వాన కోడ్ (అవసరం)",
      submit: "సమర్పించండి",
    },
  },
  ZH: {
    renderLoadingContent: {
      loadingText: "請稍等。我們根據您的要求",
    },
    renderSubmitMessageContent: {
      successMessage: "請求成功",
      clientErrorMessage: "上傳錯誤。請再試一次",
      serverErrorMessage: "上傳失敗。請再試一次",
      goBack: "回去",
    },
    renderRequestSectionContent: {
      heading: "提出請求",
      myFileText: "您的瀏覽器不支援video標籤",
      uploadVideoText: "點擊此處上傳您的視頻",
      uploadThumbnailText: "點擊此處上傳您的縮圖",
      title_: "標題（必填）",
      description_: "描述（必填）",
      audience_: "觀眾(必填)",
      madeForKids: "是的，專為兒童設計",
      notMadeForKids: "不，不適合兒童",
      visibility_: "可見性（必填）",
      select: "選擇",
      public_: "民眾",
      private_: "私人的",
      category: "類別（必填）",
      selectCategory: "選擇類別",
      creatorInvitationCode: "創作者邀請碼（必填）",
      submit: "提交",
    },
  },
  ES: {
    renderLoadingContent: {
      loadingText: "Espere por favor. Estamos a tu pedido",
    },
    renderSubmitMessageContent: {
      successMessage: "Solicitud realizada con éxito",
      clientErrorMessage: "Error al cargar. Inténtalo de nuevo",
      serverErrorMessage: "Subida fallida. Inténtalo de nuevo",
      goBack: "regresa",
    },
    renderRequestSectionContent: {
      heading: "Hacer una solicitud por",
      myFileText: "Su navegador no soporta la etiqueta de vídeo",
      uploadVideoText: "Haz clic aquí para subir tu vídeo",
      uploadThumbnailText: "Haga clic aquí para cargar su miniatura",
      title_: "Título(requerido)",
      description_: "Descripción(requerido)",
      audience_: "Audiencia (requerido)",
      madeForKids: "Si, hecho para niños",
      notMadeForKids: "No, no hecho para niños",
      visibility_: "Visibilidad (requerido)",
      select: "seleccionar",
      public_: "público",
      private_: "privado",
      category: "Categoría (requerido)",
      selectCategory: "selecciona una categoría",
      creatorInvitationCode: "Código de invitación de creador (obligatorio)",
      submit: "Entregar",
    },
  },
  FR: {
    renderLoadingContent: {
      loadingText: "S'il vous plaît, attendez. Nous sommes à votre demande",
    },
    renderSubmitMessageContent: {
      successMessage: "Demande effectuée avec succès",
      clientErrorMessage: "Erreur de téléchargement. Veuillez réessayer",
      serverErrorMessage: "Le téléchargement a échoué. Veuillez réessayer",
      goBack: "retourner",
    },
    renderRequestSectionContent: {
      heading: "Faire une demande par",
      myFileText: "Votre navigateur ne prend pas en charge la balise vidéo",
      uploadVideoText: "Cliquez ici pour télécharger votre vidéo",
      uploadThumbnailText: "Cliquez ici pour télécharger votre miniature",
      title_: "Titre (obligatoire)",
      description_: "Description (obligatoire)",
      audience_: "Public (obligatoire)",
      madeForKids: "Oui, fait pour les enfants",
      notMadeForKids: "Non, pas fait pour les enfants",
      visibility_: "Visibilité (obligatoire)",
      select: "sélectionner",
      public_: "public",
      private_: "privé",
      category: "Catégorie (obligatoire)",
      selectCategory: "Choisir une catégorie",
      creatorInvitationCode: "Code d'invitation du créateur (obligatoire)",
      submit: "Soumettre",
    },
  },
  AR: {
    renderLoadingContent: {
      loadingText: "انتظر من فضلك. نحن على طلبك",
    },
    renderSubmitMessageContent: {
      successMessage: "تم الطلب بنجاح",
      clientErrorMessage: "حدث خطأ أثناء التحميل. حاول مرة اخرى",
      serverErrorMessage: "التحميل فشل. حاول مرة اخرى",
      goBack: "عُد",
    },
    renderRequestSectionContent: {
      heading: "تقديم طلب بواسطة",
      myFileText: "متصفحك الحالي لا يدعم تشغيل الفيديو",
      uploadVideoText: "انقر هنا لتحميل الفيديو الخاص بك",
      uploadThumbnailText: "انقر هنا لتحميل الصورة المصغرة الخاصة بك",
      title_: "العنوان (مطلوب)",
      description_: "الوصف (مطلوب)",
      audience_: "الجمهور(مطلوب)",
      madeForKids: "نعم، صنعت للأطفال",
      notMadeForKids: "لا، غير مخصص للأطفال",
      visibility_: "الرؤية (مطلوب)",
      select: "يختار",
      public_: "عام",
      private_: "خاص",
      category: "الفئة (مطلوب)",
      selectCategory: "اختر الفئة",
      creatorInvitationCode: "رمز دعوة منشئ المحتوى (مطلوب)",
      submit: "يُقدِّم",
    },
  },
  BN: {
    renderLoadingContent: {
      loadingText: "অনুগ্রহপূর্বক অপেক্ষা করুন। আমরা আপনার অনুরোধে আছি",
    },
    renderSubmitMessageContent: {
      successMessage: "অনুরোধ সফলভাবে করা হয়েছে",
      clientErrorMessage:
        "আপলোড করার সময় ত্রুটি। অনুগ্রহপূর্বক আবার চেষ্টা করুন",
      serverErrorMessage: "আপলোড ব্যর্থ হয়েছে। অনুগ্রহপূর্বক আবার চেষ্টা করুন",
      goBack: "ফিরে যাও",
    },
    renderRequestSectionContent: {
      heading: "দ্বারা একটি অনুরোধ করুন",
      myFileText: "আপনার ব্রাউজার ভিডিও ট্যাগ সমর্থন করে না",
      uploadVideoText: "আপনার ভিডিও আপলোড করতে এখানে ক্লিক করুন",
      uploadThumbnailText: "আপনার থাম্বনেইল আপলোড করতে এখানে ক্লিক করুন",
      title_: "শিরোনাম (প্রয়োজনীয়)",
      description_: "বর্ণনা (প্রয়োজনীয়)",
      audience_: "দর্শক (প্রয়োজনীয়)",
      madeForKids: "হ্যাঁ, বাচ্চাদের জন্য তৈরি",
      notMadeForKids: "না, বাচ্চাদের জন্য তৈরি নয়",
      visibility_: "দৃশ্যমানতা",
      select: "নির্বাচন করুন",
      public_: "পাবলিক",
      private_: "ব্যক্তিগত",
      category: "বিভাগ (প্রয়োজনীয়)",
      selectCategory: "বিভাগ নির্বাচন করুন",
      creatorInvitationCode: "সৃষ্টিকর্তার আমন্ত্রণ কোড (প্রয়োজনীয়)",
      submit: "জমা দিন",
    },
  },
  RU: {
    renderLoadingContent: {
      loadingText: "Пожалуйста, подождите. Мы по вашему запросу",
    },
    renderSubmitMessageContent: {
      successMessage: "Запрос выполнен успешно",
      clientErrorMessage: "Ошибка загрузки. Пожалуйста, попробуйте еще раз",
      serverErrorMessage: "Загрузка не удалась. Пожалуйста, попробуйте еще раз",
      goBack: "возвращаться",
    },
    renderRequestSectionContent: {
      heading: "Сделать запрос",
      myFileText: "Ваш браузер не поддерживает видео тег",
      uploadVideoText: "Нажмите здесь, чтобы загрузить свое видео",
      uploadThumbnailText: "Нажмите здесь, чтобы загрузить миниатюру",
      title_: "Название (обязательно)",
      description_: "Описание (обязательно)",
      audience_: "Аудитория (обязательно)",
      madeForKids: "Да, сделано для детей",
      notMadeForKids: "Нет, не для детей",
      visibility_: "Видимость (обязательно)",
      select: "выбирать",
      public_: "общественный",
      private_: "частный",
      category: "Категория (обязательно)",
      selectCategory: "выберите категорию",
      creatorInvitationCode: "Пригласительный код автора (обязательно)",
      submit: "подавать",
    },
  },
  PT: {
    renderLoadingContent: {
      loadingText: "Por favor, aguarde. Estamos a seu pedido",
    },
    renderSubmitMessageContent: {
      successMessage: "Solicitação realizada com sucesso",
      clientErrorMessage: "Erro ao carregar. Por favor, tente novamente",
      serverErrorMessage: "Falha no upload. Por favor, tente novamente",
      goBack: "volte",
    },
    renderRequestSectionContent: {
      heading: "Faça uma solicitação por",
      myFileText: "Seu navegador não suporta a tag de vídeo",
      uploadVideoText: "Clique aqui para enviar seu vídeo",
      uploadThumbnailText: "Clique aqui para enviar sua miniatura",
      title_: "Título (obrigatório)",
      description_: "Descrição (obrigatório)",
      audience_: "Público-alvo (obrigatório)",
      madeForKids: "Sim, feito para crianças",
      notMadeForKids: "Não, não foi feito para crianças",
      visibility_: "Visibilidade (obrigatório)",
      select: "selecione",
      public_: "público",
      private_: "privado",
      category: "Categoria (obrigatório)",
      selectCategory: "Selecione a Categoria",
      creatorInvitationCode: "Código de convite do criador (obrigatório)",
      submit: "Enviar",
    },
  },
  UR: {
    renderLoadingContent: {
      loadingText: "Por favor, aguarde. Estamos a seu pedido",
    },
    renderSubmitMessageContent: {
      successMessage: "Solicitação realizada com sucesso",
      clientErrorMessage: "Erro ao carregar. Por favor, tente novamente",
      serverErrorMessage: "Falha no upload. Por favor, tente novamente",
      goBack: "volte",
    },
    renderRequestSectionContent: {
      heading: "Faça uma solicitação por",
      myFileText:
        "Seu navegador não suporta a tag de vídeoSeu navegador não suporta a tag de vídeo",
      uploadVideoText: "Clique aqui para enviar seu vídeo",
      uploadThumbnailText: "Clique aqui para enviar sua miniatura",
      title_: "Título (obrigatório)",
      description_: "Descrição (obrigatório)",
      audience_: "Público-alvo (obrigatório)",
      madeForKids: "Sim, feito para crianças",
      notMadeForKids: "Não, não foi feito para crianças",
      visibility_: "Visibilidade (obrigatório)",
      select: "selecione",
      public_: "público",
      private_: "privado",
      category: "Categoria (obrigatório)",
      selectCategory: "Selecione a Categoria",
      creatorInvitationCode: "Código de convite do criador (obrigatório)",
      submit: "Enviar",
    },
  },
};

export const youtubeCategories = [
  { category: "Film & Animation", id: 1 },
  { category: "Autos & Vehicles", id: 2 },
  { category: "Music", id: 10 },
  { category: "Pets & Animals", id: 15 },
  { category: "Sports", id: 17 },
  { category: "Short Movies", id: 18 },
  { category: "Travel & Events", id: 19 },
  { category: "Gaming", id: 20 },
  { category: "Videoblogging", id: 21 },
  { category: "People & Blogs", id: 22 },
  { category: "Comedy", id: 23 },
  { category: "Entertainment", id: 24 },
  { category: "News & Politics", id: 25 },
  { category: "Howto & Style", id: 26 },
  { category: "Education", id: 27 },
  { category: "Science & Technology", id: 28 },
  { category: "Nonprofits & Activism", id: 29 },
  { category: "Movies", id: 30 },
  { category: "Anime/Animation", id: 31 },
  { category: "Action/Adventure", id: 32 },
  { category: "Classics", id: 33 },
  { category: "Documentary", id: 35 },
  { category: "Drama", id: 36 },
  { category: "Family", id: 37 },
  { category: "Foreign", id: 38 },
  { category: "Horror", id: 39 },
  { category: "Sci-Fi/Fantasy", id: 40 },
  { category: "Thriller", id: 41 },
  { category: "Shorts", id: 42 },
  { category: "Shows", id: 43 },
  { category: "Trailers", id: 44 },
];
